#!/usr/bin/env python3
"""skatkindprob butler — the project's single entry point.

This file is a bootstrap shim, not the implementation. It makes sure a cached
virtualenv with the butler harness exists, then hands off to it. Everything the
commands actually do lives in the harness; what this project does specifically
is declared in butler.toml (and butler_tasks.py, if it has one).

    python butler.py --help

Deliberate properties:

  * stdlib only, so it runs on a bare interpreter with nothing installed;
  * the harness version is pinned by HARNESS_REF below and nothing else, so a
    project is never silently upgraded — bump it when you mean to;
  * offline-safe: once the venv exists nothing touches the network;
  * BUTLER_HARNESS_PATH=/path/to/butler runs a harness working tree directly
    instead of the cached venv. That is how the harness itself is developed,
    and how CI uses a checkout of the harness rather than installing it.
  * BUTLER_HARNESS_URL overrides where the harness is fetched from, without
    editing this file — for a fork, a mirror, or an air-gapped build.

Generated by `butler new`. It should not need editing except to bump the pin.
"""

import os
import subprocess
import sys
from pathlib import Path

HARNESS_URL = "git+https://github.com/vaelum/butler-harness.git"
HARNESS_REF = "v0.6.6"

PROJECT_ROOT = Path(__file__).resolve().parent


def venv_python(venv: Path) -> Path:
    return venv_script(venv, "python.exe" if os.name == "nt" else "python")


def venv_script(venv: Path, name: str) -> Path:
    return venv / ("Scripts" if os.name == "nt" else "bin") / name


def cache_venv() -> Path:
    base = Path(os.environ.get("XDG_CACHE_HOME", Path.home() / ".cache"))
    # Keyed by the pin, so several projects on different refs coexist and a bump
    # builds a new venv instead of mutating the one other projects are using.
    return base / "butler" / "venvs" / HARNESS_REF.replace("/", "-")


def bootstrap(venv: Path) -> Path:
    py = venv_python(venv)
    if py.exists():
        return py
    print(f"butler: preparing the harness ({HARNESS_REF}) in {venv} …", file=sys.stderr)
    venv.parent.mkdir(parents=True, exist_ok=True)
    url = os.environ.get("BUTLER_HARNESS_URL", HARNESS_URL)
    spec = f"butler-harness @ {url}@{HARNESS_REF}"
    try:
        subprocess.check_call([sys.executable, "-m", "venv", str(venv)])
        subprocess.check_call([str(py), "-m", "pip", "install", "--quiet",
                               "--disable-pip-version-check", spec])
    except (subprocess.CalledProcessError, OSError) as e:
        # Leave nothing half-built: a partial venv would be reused forever.
        shutil_rmtree(venv)
        print(f"butler: could not install the harness ({e}).\n"
              f"        Install it by hand and re-run:\n"
              f"          python -m venv {venv}\n"
              f"          {py} -m pip install '{spec}'", file=sys.stderr)
        raise SystemExit(1)
    return py


def shutil_rmtree(path: Path) -> None:
    import shutil

    shutil.rmtree(path, ignore_errors=True)


def main() -> None:
    # The project root travels in the environment so butler works from any cwd.
    os.environ["BUTLER_PROJECT_ROOT"] = str(PROJECT_ROOT)

    dev_path = os.environ.get("BUTLER_HARNESS_PATH")
    if dev_path:
        sys.path.insert(0, str(Path(dev_path).expanduser().resolve() / "src"))
        from butler.__main__ import main as run

        raise SystemExit(run())

    venv = cache_venv()
    py = bootstrap(venv)

    # Hand off via the venv's console script, NOT `python -m butler`. This file
    # is called butler.py and sits in the project root, which `-m` puts on
    # sys.path ahead of site-packages — so `import butler` would find THIS FILE
    # instead of the installed package and re-exec the shim, forever. A console
    # script's sys.path[0] is the venv's bin directory, so nothing here shadows
    # anything.
    entry = venv_script(venv, "butler.exe" if os.name == "nt" else "butler")
    if entry.exists():
        os.execv(str(entry), [str(entry), *sys.argv[1:]])
    # Fallback for an older install without the console script. -P (3.11+)
    # keeps the script's directory off sys.path, which closes the same hole.
    os.execv(str(py), [str(py), "-P", "-m", "butler", *sys.argv[1:]])


if __name__ == "__main__":
    main()
